#:kivy 2.2.0
<OptionsScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Optionen'
            font_size: '24sp'

        # Music toggle button
        ToggleButton:
            id: music_button
            text: 'Musik: An' if app.game_state.music_enabled else 'Musik: Ab'
            on_release: root.toggle_music()

        # Sound effects toggle button
        ToggleButton:
            id: soundfx_button
            text: 'Sound-Effekte: An' if app.game_state.soundfx_enabled else 'Sound-Effekte: Ab'
            on_release: root.toggle_soundfx()

        Button:
            text: 'Zurück zum Haupmenü'
            on_release: app.root.current = 'menu'

<IntroScreen>:
    CustomCarousel:
        id: intro_carousel
        direction: 'right'
        Image:
            source: 'Verabschiedung_text.png'
            allow_stretch: True
            keep_ratio: True
            #Damit das Bild dem Smartphone angepasst wird(ChatGPT)
        Image:
            source: 'neues_Haus_text.png'
            allow_stretch: True
            keep_ratio: True
        Image:
            source: 'im_haus_text.png'
            allow_stretch: True
            keep_ratio: True
        Image:
            source: 'die_Reise_beginnt_text.png'
            allow_stretch: True
            keep_ratio: True

<MainMenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Lolas kleine Abenteuer'
        Button:
            text: 'Neues Spiel'
            background_color: 0.494, 1, 0.973, 1 
            on_press: root.start_new_game()
        Button:
            id: continue_button
            text: 'Spiel fortsetzen' if not root.is_all_found() else 'Game Over'
            background_color: (0.494, 1, 0.973, 1) if not root.is_all_found() else (.5, .5, .5, 1)
            on_press: app.root.current = 'levels'
            disabled: root.is_all_found()
        Button:
            text: 'Optionen'
            background_color: 0.494, 1, 0.973, 1
            on_release: app.root.current = 'options'
        Button:
            text: 'Infos'
            background_color: 0.494, 1, 0.973, 1
            on_release: app.root.current = 'infos'
        Button:
            text: 'Exit'
            background_color: 0.859, 0.255, 0.686, 1
            on_press: app.stop()

<InfosScreen>:
    BoxLayout:
        orientation: 'vertical'
        Image:
            source: 'infos2.png' 
            allow_stretch: True
            keep_ratio: False 
        

    AnchorLayout:  #ChatGPT, damit der Knopf rechts im Ecken ist
        anchor_x: 'right'
        anchor_y: 'top'
        Button:
            text: 'Zurück'
            size_hint: None, None
            size: 150,75
            pos_hint: {'top': 1, 'right': 1}
            on_press: root.back_button_press()
            
<LevelSelecterScreen>:
    BoxLayout:
        orientation: 'vertical'
        Image:
            source: 'haus_levels.png' 
            allow_stretch: True
            keep_ratio: False 
            on_touch_down: root.on_house_click(*args) 


    AnchorLayout:  #ChatGPT, damit der Knopf rechts im Ecken ist
        anchor_x: 'right'
        anchor_y: 'top'
        Button:
            text: 'Zurück'
            size_hint: None, None
            size: 150,75
            pos_hint: {'top': 1, 'right': 1}
            on_press: root.back_button_press()
    
            
<GameScreen>:
    id: game_screen    
    BoxLayout:
        orientation: 'horizontal'
        # Game area (90% of width)
        HiddenObjectGame:
            size_hint_x: 0.9
            id: game_area

            canvas.before:
                StencilPush
                Rectangle:
                    pos: self.pos
                    size: self.size
                StencilUse


            canvas.after:
                StencilUnUse
                Rectangle:
                    pos: self.pos
                    size: self.size
                StencilPop

        # Status area (10% of width)
        BoxLayout:
            orientation: 'vertical'
            id: status_area
            size_hint_x: 0.1
            padding: 5  # Add some padding around the status items
            spacing: 5  # Add some space between status items
<OutroScreen>:
    CustomCarousel:
        id: outro_carousel
        direction: 'right'
        Image:
            source: 'haus_zurueck.png'
            allow_stretch: True
            keep_ratio: True
            #Damit das Bild dem Smartphone angepasst wird(ChatGPT)
        Image:
            source: 'haus_fertig.png'
            allow_stretch: True
            keep_ratio: True
        Image:
            source: 'fest_text.png'
            allow_stretch: True
            keep_ratio: True
        Image:
            source: 'galaxie.jpg'
            allow_stretch: True
            keep_ratio: True
